lint_stubs/xilinx/BUFG_GT.sv
lint_stubs/xilinx/GTXE2_COMMON.sv
lint_stubs/xilinx/qeciphy_clk_mmcm.sv
lint_stubs/xilinx/qeciphy_gty_transceiver.sv
lint_stubs/xilinx/qeciphy_gtx_transceiver.sv
lint_stubs/xilinx/qeciphy_gth_transceiver.sv
lint_stubs/altera/qeciphy_etile.sv
lint_stubs/altera/qeciphy_ftile.sv
lint_stubs/altera/qeciphy_altera_clk_mmcm.sv
lint_stubs/altera/tennm_lcell_comb.sv
