set_location_assignment PIN_AJ12 -to gt_refclk_in_p
set_location_assignment PIN_CU50 -to clk_100_p
set_location_assignment PIN_BF1 -to GT_TXP
set_location_assignment PIN_BE2 -to GT_TXN
set_location_assignment PIN_BF7 -to GT_RXP
set_location_assignment PIN_BE8 -to GT_RXN
set_location_assignment PIN_H21 -to i2c_qsfpdd0_scl
set_location_assignment PIN_H23 -to i2c_qsfpdd0_sda
#set_location_assignment PIN_DA20 -to qsfpdd0_reset_L
#set_location_assignment PIN_CT29 -to qsfpdd0_modprs_L
#set_location_assignment PIN_DB21 -to qsfpdd0_Initmode
#set_location_assignment PIN_DB19 -to qsfpdd0_modsel_L
set_location_assignment PIN_CR54 -to fpga_led[0]
set_location_assignment PIN_DB57 -to fpga_led[1]
set_location_assignment PIN_CY57 -to fpga_led[2]
set_location_assignment PIN_CU52 -to fpga_led[3]