# SPDX-License-Identifier: BSD-2-Clause
# Copyright (c) 2026 Riverlane Ltd.

# Extracts the GT COMMON primitive attribute values that Vivado's gtwizard_ultrascale chose for a
# given customization, and writes them as a SystemVerilog parameter-override fragment for
# qeciphy_gty_common.sv / qeciphy_gth_common.sv to `include.
#
# Inputs are the two files open_example_project generates for a LOCATE_COMMON=EXAMPLE_DESIGN core
# (copied out by vendors/xilinx/qeciphy_gt{y,h}_transceiver.tcl):
#   <ip>_gt{y,h}e4_common_wrapper.v         - sets every <PRIM>_<ATTR> parameter for this customization
#   gtwizard_ultrascale_v1_7_gt{y,h}e4_common.v - maps each <PRIM>_<ATTR> onto the primitive's <ATTR>
#
# Usage: gen_gt_common_attrs.py <PRIM> <wrapper.v> <common_module.v> <out.svh>
#        gen_gt_common_attrs.py <PRIM> --placeholder <out.svh>

import re
import sys

# Set explicitly by qeciphy_gt{y,h}_common.sv; LOC is never a valid override here.
EXCLUDED_PREFIXES = ("SIM_",)
EXCLUDED = {"LOC"}


def primitive_attrs(prim, module_src):
    """Attribute names the wizard's common module maps 1:1 onto the primitive."""
    start = module_src.index(f"{prim} #(")
    end = module_src.index(f") {prim}_PRIM_INST", start)
    attrs = []
    for attr, src in re.findall(r"\.(\w+)\s*\(\s*(\w+)\s*\)", module_src[start:end]):
        if src != f"{prim}_{attr}":
            sys.exit(f"ERROR: {prim}.{attr} is driven by '{src}', expected '{prim}_{attr}'")
        attrs.append(attr)
    return attrs


def wrapper_values(prim, wrapper_src):
    """<PRIM>_<ATTR> -> value from the wrapper's parameter-override block."""
    start = wrapper_src.index("_common #(")
    end = wrapper_src.index(") common_inst", start)
    return dict(re.findall(rf"\.{prim}_(\w+)\s*\(\s*([^)]*?)\s*\)", wrapper_src[start:end]))


def main():
    if len(sys.argv) == 4 and sys.argv[2] == "--placeholder":
        prim, out = sys.argv[1], sys.argv[3]
        with open(out, "w") as f:
            f.write(f"// Generated by scripts/gen_gt_common_attrs.py - placeholder, no {prim} in this build.\n")
        return

    if len(sys.argv) != 5:
        print("Usage: gen_gt_common_attrs.py <PRIM> <wrapper.v> <common_module.v> <out.svh>")
        print("       gen_gt_common_attrs.py <PRIM> --placeholder <out.svh>")
        sys.exit(1)

    prim, wrapper_file, module_file, out = sys.argv[1:]
    with open(wrapper_file) as f:
        wrapper_src = f.read()
    with open(module_file) as f:
        module_src = f.read()

    values = wrapper_values(prim, wrapper_src)
    lines = []
    for attr in primitive_attrs(prim, module_src):
        if attr in EXCLUDED or attr.startswith(EXCLUDED_PREFIXES):
            continue
        if attr not in values:
            sys.exit(f"ERROR: {wrapper_file} does not set {prim}_{attr}")
        lines.append(f"    , .{attr}({values[attr]})\n")

    with open(out, "w") as f:
        f.write(f"// Generated by scripts/gen_gt_common_attrs.py from {wrapper_file.split('/')[-1]} - do not edit.\n")
        f.write(f"// {prim} attribute overrides chosen by gtwizard_ultrascale for this build's customization.\n")
        f.writelines(lines)
    print(f"INFO: Wrote {len(lines)} {prim} attributes to {out}")


if __name__ == "__main__":
    main()
