# SPDX-License-Identifier: None
# Copyright (c) 2025 Riverlane Ltd.

# Vivado script to generate simulation files for XCI cores
# Usage: vivado -mode batch -source vivado_generate_xci_sim_files.tcl -tclargs <PART> <XCI_FILES>

if { !([info exists ::argv] && [llength $::argv] >= 1) } {
    puts "ERROR: Usage: vivado -mode batch -source vivado_generate_xci_sim_files.tcl -tclargs <PART> <XCI_FILES>"
    exit 1
}

set part_number [lindex $::argv 0]
set xci_files [lrange $::argv 1 end]

puts "INFO: Generating simulation files for part: $part_number"
puts "INFO: XCI files: $xci_files"

# Create temporary project for simulation file generation
set output_dir "./run/xci_sim_gen"
create_project xci_sim_gen $output_dir -part $part_number -force

# Set project properties for simulation
set_property target_language Verilog [current_project]
set_property simulator_language Mixed [current_project]

# Import all XCI files
foreach xci_file $xci_files {
    if {$xci_file ne ""} {
        puts "INFO: Importing XCI file: $xci_file"
        import_ip $xci_file
    }
}

# Refresh IP repository
if {[catch {update_ip_catalog} error_msg]} {
    puts "WARNING: Failed to update IP catalog: $error_msg"
}

# Get all imported IP cores
set ip_cores [get_ips]
puts "INFO: Found [llength $ip_cores] IP cores to process"

# Create simulation files directory
file mkdir tb/sim_files
file mkdir tb/sim_files/ip_user_files
file mkdir tb/sim_files/ipstatic

# Generate simulation files for each IP
foreach ip_core $ip_cores {
    set ip_name [get_property NAME $ip_core]
    puts "INFO: Generating simulation files for IP: $ip_name"
    
    # Generate simulation netlist and files
    generate_target simulation $ip_core
    
    # Export simulation files - this creates the encrypted simulation models
    export_simulation -of_objects $ip_core -directory tb/sim_files -ip_user_files_dir tb/sim_files/ip_user_files -ipstatic_source_dir tb/sim_files/ipstatic -lib_map_path tb/sim_files/lib_map -use_ip_compiled_libs -force
    
    puts "INFO: Simulation files generated for $ip_name"
}

# Generate compile order file for external simulators
set compile_order_file "tb/sim_files/compile_order.f"
set fp [open $compile_order_file w]

puts $fp "# Simulation file list generated by Vivado"
puts $fp "# Use this file with external simulators (ModelSim, Questa, VCS, Xcelium)"
puts $fp ""

# Add library map file if it exists
if {[file exists tb/sim_files/lib_map]} {
    puts $fp "# Library mappings"
    puts $fp "-f tb/sim_files/lib_map"
    puts $fp ""
}

# Add include directories
puts $fp "# Include directories"
puts $fp "+incdir+tb/sim_files/ipstatic"
puts $fp "+incdir+tb/sim_files/ip_user_files/sim_scripts"
puts $fp ""

# Find and add all simulation source files
puts $fp "# Simulation source files"
set sim_files [glob -nocomplain tb/sim_files/**/*.v tb/sim_files/**/*.sv]
foreach sim_file $sim_files {
    puts $fp $sim_file
}

close $fp
puts "INFO: Compile order file written to: $compile_order_file"

puts "INFO: Simulation file generation complete"
puts "INFO: Files generated in tb/sim_files/"
puts "INFO: - compile_order.f: File list for external simulators"
puts "INFO: - Encrypted simulation models in subdirectories"
puts "INFO: - Use Vivado-generated simulator scripts in subdirectories"

# Close project
close_project