// Copyright 2024 Intel Corporation.
//
// This reference design file is subject licensed to you by the terms and 
// conditions of the applicable License Terms and Conditions for Hardware 
// Reference Designs and/or Design Examples (either as signed by you or 
// found at https://www.altera.com/common/legal/leg-license_agreement.html ).  
//
// As stated in the license, you agree to only use this reference design 
// solely in conjunction with Intel FPGAs or Intel CPLDs.  
//
// THE REFERENCE DESIGN IS PROVIDED "AS IS" WITHOUT ANY EXPRESS OR IMPLIED
// WARRANTY OF ANY KIND INCLUDING WARRANTIES OF MERCHANTABILITY, 
// NONINFRINGEMENT, OR FITNESS FOR A PARTICULAR PURPOSE. Intel does not 
// warrant or assume responsibility for the accuracy or completeness of any
// information, links or other items within the Reference Design and any 
// accompanying materials.
//
// In the event that you do not agree with such terms and conditions, do not
// use the reference design file.
/////////////////////////////////////////////////////////////////////////////

// Generated by one of Gregg's toys on Mon Jan 15 15:54:16 2024

`timescale 1ps / 1ps

module eth_8b10b_enc_a (
    input clk,
    input sclr,
    input din_k,
    input din_ena,
    input [7:0] din_dat,
    input din_rd,
    output dout_val,
    output [9:0] dout_dat,
    output dout_rdcomb,
    output dout_rdreg
);


   // baeckler - 04-10-2006
   // reworked a little for new chips 03-01-2013

   // an 8b10b encoder, based on files from Martin R and IBM paper

   // DESCRIPTION
   // 
   //  8B10B coding is designed to maintain an equal number of ones and zeros on the coded stream, and to
   // limit run length to five bits. Additionally, it has a mechanism for sending control characters and some
   // error detection capability. The 8B10B encoder is composed of a 5B/6B coder and a 3B/4B coder
   // operating in a loosely coupled fashion as illustrated in the figure below.
   // 
   // The running disparity, or rd, signals balance ones and zeros over time. If an encoded result contains a
   // surplus of either bit, the rd signal directs downstream coders to restore the balance. The 5-bit run-
   // length is enforced by construction. The K signal is used to transmit control characters. Only some of the
   // 8-bit inputs represent legal control characters. K28.5 is the standard link synchronization or idle
   // character, although K28.7 and K28.1 are also suitable. The following table shows the legal K control
   // characters.
   // 
   // Table : legal K characters
   // K28.0 8'b000_11100
   // K28.1 8'b001_11100
   // K28.2 8'b010_11100
   // K28.3 8'b011_11100
   // K28.4 8'b100_11100
   // K28.5 8'b101_11100 (comma)
   // K28.6 8'b110_11100
   // K28.7 8'b111_11100
   // K23.7 8'b111_10111
   // K27.7 8'b111_11011
   // K29.7 8'b111_11101
   // K30.7 8'b111_11110
   // 
   //    din_k,		// Data in is a special code, not all are legal.	
   //    din_ena,		// Data (or code) input enable
   //    din_dat,		// 8b data in
   //    din_rd,			// running disparity input
   //    dout_val,		// data out is valid
   //    dout_dat,		// data out
   //    dout_rdcomb,	// running disparity output (comb)
   //    dout_rdreg		// running disparity output (reg)


   reg        dout_val_r = 1'b0;
   reg  [9:0] dout_dat_r = 10'b0;

   wire       A = din_dat[0];
   wire       B = din_dat[1];
   wire       C = din_dat[2];
   wire       D = din_dat[3];
   wire       E = din_dat[4];
   wire       F = din_dat[5];
   wire       G = din_dat[6];
   wire       H = din_dat[7];
   wire       K = din_k;

   reg        rd1_part  /* synthesis keep */;
   reg        rd1;

   reg        dout_rdcomb_r;
   reg        dout_rdreg_r = 1'b0;
   reg        SorK;
   reg a, b, c, d, e, f, g, h, i, j;

   wire rdout_x, rdout_y;

   tennm_lcell_comb #(
       .lut_mask(64'h157E7EE800000000),
       .extended_lut("off"),
       .shared_arith("off")
   ) wlc0 (
       .dataa(!B),
       .datab(!D),
       .datac(!E),
       .datad(!A),
       .datae(!C),
       .dataf(!K),
       .datag(1'b1),
       .datah(1'b1),
       .cin(1'b0),
       // synthesis translate_off
       .sharein(1'b0),
       // synthesis translate_on
       .sumout(),
       .cout(),
       // synthesis translate_off
       .shareout(),
       // synthesis translate_on
       .combout(rdout_x)
   );

   tennm_lcell_comb #(
       .lut_mask(64'h3CC99663699CC336),
       .extended_lut("off"),
       .shared_arith("off")
   ) wlc1 (
       .dataa(!H),
       .datab(!din_rd),
       .datac(!F),
       .datad(!G),
       .datae(!rdout_x),
       .dataf(!rdout_x),
       .datag(1'b1),
       .datah(1'b1),
       .cin(1'b0),
       // synthesis translate_off
       .sharein(1'b0),
       // synthesis translate_on
       .sumout(),
       .cout(),
       // synthesis translate_off
       .shareout(),
       // synthesis translate_on
       .combout(rdout_y)
   );


   always @(*) begin
      dout_rdcomb_r = rdout_y;

      case ({
         din_rd, din_dat[4:0], din_k
      })
         7'h00: {i, e, d, c, b, a} = 6'h39;
         7'h01: {i, e, d, c, b, a} = 6'h39;
         7'h02: {i, e, d, c, b, a} = 6'h2e;
         7'h03: {i, e, d, c, b, a} = 6'h2e;
         7'h04: {i, e, d, c, b, a} = 6'h2d;
         7'h05: {i, e, d, c, b, a} = 6'h2d;
         7'h06: {i, e, d, c, b, a} = 6'h23;
         7'h07: {i, e, d, c, b, a} = 6'h23;
         7'h08: {i, e, d, c, b, a} = 6'h2b;
         7'h09: {i, e, d, c, b, a} = 6'h2b;
         7'h0a: {i, e, d, c, b, a} = 6'h25;
         7'h0b: {i, e, d, c, b, a} = 6'h25;
         7'h0c: {i, e, d, c, b, a} = 6'h26;
         7'h0d: {i, e, d, c, b, a} = 6'h26;
         7'h0e: {i, e, d, c, b, a} = 6'h07;
         7'h0f: {i, e, d, c, b, a} = 6'h07;
         7'h10: {i, e, d, c, b, a} = 6'h27;
         7'h11: {i, e, d, c, b, a} = 6'h27;
         7'h12: {i, e, d, c, b, a} = 6'h29;
         7'h13: {i, e, d, c, b, a} = 6'h29;
         7'h14: {i, e, d, c, b, a} = 6'h2a;
         7'h15: {i, e, d, c, b, a} = 6'h2a;
         7'h16: {i, e, d, c, b, a} = 6'h0b;
         7'h17: {i, e, d, c, b, a} = 6'h0b;
         7'h18: {i, e, d, c, b, a} = 6'h2c;
         7'h19: {i, e, d, c, b, a} = 6'h2c;
         7'h1a: {i, e, d, c, b, a} = 6'h0d;
         7'h1b: {i, e, d, c, b, a} = 6'h0d;
         7'h1c: {i, e, d, c, b, a} = 6'h0e;
         7'h1d: {i, e, d, c, b, a} = 6'h0e;
         7'h1e: {i, e, d, c, b, a} = 6'h3a;
         7'h1f: {i, e, d, c, b, a} = 6'h3a;
         7'h20: {i, e, d, c, b, a} = 6'h36;
         7'h21: {i, e, d, c, b, a} = 6'h36;
         7'h22: {i, e, d, c, b, a} = 6'h31;
         7'h23: {i, e, d, c, b, a} = 6'h31;
         7'h24: {i, e, d, c, b, a} = 6'h32;
         7'h25: {i, e, d, c, b, a} = 6'h32;
         7'h26: {i, e, d, c, b, a} = 6'h13;
         7'h27: {i, e, d, c, b, a} = 6'h33;
         7'h28: {i, e, d, c, b, a} = 6'h34;
         7'h29: {i, e, d, c, b, a} = 6'h34;
         7'h2a: {i, e, d, c, b, a} = 6'h15;
         7'h2b: {i, e, d, c, b, a} = 6'h35;
         7'h2c: {i, e, d, c, b, a} = 6'h16;
         7'h2d: {i, e, d, c, b, a} = 6'h36;
         7'h2e: {i, e, d, c, b, a} = 6'h17;
         7'h2f: {i, e, d, c, b, a} = 6'h17;
         7'h30: {i, e, d, c, b, a} = 6'h33;
         7'h31: {i, e, d, c, b, a} = 6'h33;
         7'h32: {i, e, d, c, b, a} = 6'h19;
         7'h33: {i, e, d, c, b, a} = 6'h39;
         7'h34: {i, e, d, c, b, a} = 6'h1a;
         7'h35: {i, e, d, c, b, a} = 6'h3a;
         7'h36: {i, e, d, c, b, a} = 6'h1b;
         7'h37: {i, e, d, c, b, a} = 6'h1b;
         7'h38: {i, e, d, c, b, a} = 6'h1c;
         7'h39: {i, e, d, c, b, a} = 6'h3c;
         7'h3a: {i, e, d, c, b, a} = 6'h1d;
         7'h3b: {i, e, d, c, b, a} = 6'h1d;
         7'h3c: {i, e, d, c, b, a} = 6'h1e;
         7'h3d: {i, e, d, c, b, a} = 6'h1e;
         7'h3e: {i, e, d, c, b, a} = 6'h35;
         7'h3f: {i, e, d, c, b, a} = 6'h35;
         7'h40: {i, e, d, c, b, a} = 6'h06;
         7'h41: {i, e, d, c, b, a} = 6'h39;
         7'h42: {i, e, d, c, b, a} = 6'h11;
         7'h43: {i, e, d, c, b, a} = 6'h2e;
         7'h44: {i, e, d, c, b, a} = 6'h12;
         7'h45: {i, e, d, c, b, a} = 6'h2d;
         7'h46: {i, e, d, c, b, a} = 6'h23;
         7'h47: {i, e, d, c, b, a} = 6'h1c;
         7'h48: {i, e, d, c, b, a} = 6'h14;
         7'h49: {i, e, d, c, b, a} = 6'h2b;
         7'h4a: {i, e, d, c, b, a} = 6'h25;
         7'h4b: {i, e, d, c, b, a} = 6'h1a;
         7'h4c: {i, e, d, c, b, a} = 6'h26;
         7'h4d: {i, e, d, c, b, a} = 6'h19;
         7'h4e: {i, e, d, c, b, a} = 6'h38;
         7'h4f: {i, e, d, c, b, a} = 6'h38;
         7'h50: {i, e, d, c, b, a} = 6'h18;
         7'h51: {i, e, d, c, b, a} = 6'h27;
         7'h52: {i, e, d, c, b, a} = 6'h29;
         7'h53: {i, e, d, c, b, a} = 6'h16;
         7'h54: {i, e, d, c, b, a} = 6'h2a;
         7'h55: {i, e, d, c, b, a} = 6'h15;
         7'h56: {i, e, d, c, b, a} = 6'h0b;
         7'h57: {i, e, d, c, b, a} = 6'h34;
         7'h58: {i, e, d, c, b, a} = 6'h2c;
         7'h59: {i, e, d, c, b, a} = 6'h13;
         7'h5a: {i, e, d, c, b, a} = 6'h0d;
         7'h5b: {i, e, d, c, b, a} = 6'h32;
         7'h5c: {i, e, d, c, b, a} = 6'h0e;
         7'h5d: {i, e, d, c, b, a} = 6'h31;
         7'h5e: {i, e, d, c, b, a} = 6'h05;
         7'h5f: {i, e, d, c, b, a} = 6'h3a;
         7'h60: {i, e, d, c, b, a} = 6'h09;
         7'h61: {i, e, d, c, b, a} = 6'h09;
         7'h62: {i, e, d, c, b, a} = 6'h31;
         7'h63: {i, e, d, c, b, a} = 6'h0e;
         7'h64: {i, e, d, c, b, a} = 6'h32;
         7'h65: {i, e, d, c, b, a} = 6'h0d;
         7'h66: {i, e, d, c, b, a} = 6'h13;
         7'h67: {i, e, d, c, b, a} = 6'h0c;
         7'h68: {i, e, d, c, b, a} = 6'h34;
         7'h69: {i, e, d, c, b, a} = 6'h0b;
         7'h6a: {i, e, d, c, b, a} = 6'h15;
         7'h6b: {i, e, d, c, b, a} = 6'h0a;
         7'h6c: {i, e, d, c, b, a} = 6'h16;
         7'h6d: {i, e, d, c, b, a} = 6'h09;
         7'h6e: {i, e, d, c, b, a} = 6'h28;
         7'h6f: {i, e, d, c, b, a} = 6'h28;
         7'h70: {i, e, d, c, b, a} = 6'h0c;
         7'h71: {i, e, d, c, b, a} = 6'h33;
         7'h72: {i, e, d, c, b, a} = 6'h19;
         7'h73: {i, e, d, c, b, a} = 6'h06;
         7'h74: {i, e, d, c, b, a} = 6'h1a;
         7'h75: {i, e, d, c, b, a} = 6'h05;
         7'h76: {i, e, d, c, b, a} = 6'h24;
         7'h77: {i, e, d, c, b, a} = 6'h24;
         7'h78: {i, e, d, c, b, a} = 6'h1c;
         7'h79: {i, e, d, c, b, a} = 6'h03;
         7'h7a: {i, e, d, c, b, a} = 6'h22;
         7'h7b: {i, e, d, c, b, a} = 6'h22;
         7'h7c: {i, e, d, c, b, a} = 6'h21;
         7'h7d: {i, e, d, c, b, a} = 6'h21;
         7'h7e: {i, e, d, c, b, a} = 6'h0a;
         7'h7f: {i, e, d, c, b, a} = 6'h0a;
      endcase

      case (din_dat[4:0])
         5'h00: rd1_part = 1'b1;
         5'h01: rd1_part = 1'b1;
         5'h02: rd1_part = 1'b1;
         5'h03: rd1_part = 1'b0;
         5'h04: rd1_part = 1'b1;
         5'h05: rd1_part = 1'b0;
         5'h06: rd1_part = 1'b0;
         5'h07: rd1_part = 1'b0;
         5'h08: rd1_part = 1'b1;
         5'h09: rd1_part = 1'b0;
         5'h0a: rd1_part = 1'b0;
         5'h0b: rd1_part = 1'b0;
         5'h0c: rd1_part = 1'b0;
         5'h0d: rd1_part = 1'b0;
         5'h0e: rd1_part = 1'b0;
         5'h0f: rd1_part = 1'b1;
         5'h10: rd1_part = 1'b1;
         5'h11: rd1_part = 1'b0;
         5'h12: rd1_part = 1'b0;
         5'h13: rd1_part = 1'b0;
         5'h14: rd1_part = 1'b0;
         5'h15: rd1_part = 1'b0;
         5'h16: rd1_part = 1'b0;
         5'h17: rd1_part = 1'b1;
         5'h18: rd1_part = 1'b1;
         5'h19: rd1_part = 1'b0;
         5'h1a: rd1_part = 1'b0;
         5'h1b: rd1_part = 1'b1;
         5'h1c: rd1_part = 1'b0;
         5'h1d: rd1_part = 1'b1;
         5'h1e: rd1_part = 1'b1;
         5'h1f: rd1_part = 1'b1;
      endcase
   end

   wire disp4 = (!F & !G);
   wire disp5 = (F & G);
   wire disp6 = ((F ^ G) & K);
   wire invert_fj = !(((rd1_part | K) ^ din_rd) ? disp5 : (disp4 | disp6));

   always @(*) begin
      g = (!(!F & !H) & !G) ^ invert_fj;
      h = (!H) ^ invert_fj;
   end

   wire f0, f1, f2, f3, f4;

   tennm_lcell_comb #(
       .lut_mask(64'h0224244002242440),
       .extended_lut("off"),
       .shared_arith("off")
   ) wlc2 (
       .dataa(!din_dat[3]),
       .datab(!din_dat[4]),
       .datac(!din_dat[1]),
       .datad(!din_dat[2]),
       .datae(!din_dat[0]),
       .dataf(1'b1),
       .datag(1'b1),
       .datah(1'b1),
       .cin(1'b0),
       // synthesis translate_off
       .sharein(1'b0),
       // synthesis translate_on
       .sumout(),
       .cout(),
       // synthesis translate_off
       .shareout(),
       // synthesis translate_on
       .combout(f0)
   );

   tennm_lcell_comb #(
       .lut_mask(64'h0F03AA590F03AA59),
       .extended_lut("off"),
       .shared_arith("off")
   ) wlc3 (
       .dataa(!din_rd),
       .datab(!din_dat[7]),
       .datac(!din_dat[6]),
       .datad(!din_dat[5]),
       .datae(!din_k),
       .dataf(1'b1),
       .datag(1'b1),
       .datah(1'b1),
       .cin(1'b0),
       // synthesis translate_off
       .sharein(1'b0),
       // synthesis translate_on
       .sumout(),
       .cout(),
       // synthesis translate_off
       .shareout(),
       // synthesis translate_on
       .combout(f1)
   );

   tennm_lcell_comb #(
       .lut_mask(64'h00F355A600F355A6),
       .extended_lut("off"),
       .shared_arith("off")
   ) wlc4 (
       .dataa(!din_rd),
       .datab(!din_dat[7]),
       .datac(!din_dat[6]),
       .datad(!din_dat[5]),
       .datae(!din_k),
       .dataf(1'b1),
       .datag(1'b1),
       .datah(1'b1),
       .cin(1'b0),
       // synthesis translate_off
       .sharein(1'b0),
       // synthesis translate_on
       .sumout(),
       .cout(),
       // synthesis translate_off
       .shareout(),
       // synthesis translate_on
       .combout(f2)
   );

   tennm_lcell_comb #(
       .lut_mask(64'h7800FF597800FF59),
       .extended_lut("off"),
       .shared_arith("off")
   ) wlc5 (
       .dataa(!f4),
       .datab(!f0),
       .datac(!din_rd),
       .datad(!f1),
       .datae(!f2),
       .dataf(1'b1),
       .datag(1'b1),
       .datah(1'b1),
       .cin(1'b0),
       // synthesis translate_off
       .sharein(1'b0),
       // synthesis translate_on
       .sumout(),
       .cout(),
       // synthesis translate_off
       .shareout(),
       // synthesis translate_on
       .combout(f3)
   );

   tennm_lcell_comb #(
       .lut_mask(64'h055E5EE8055E5EE8),
       .extended_lut("off"),
       .shared_arith("off")
   ) wlc6 (
       .dataa(!din_dat[3]),
       .datab(!din_dat[4]),
       .datac(!din_dat[1]),
       .datad(!din_dat[2]),
       .datae(!din_dat[0]),
       .dataf(1'b1),
       .datag(1'b1),
       .datah(1'b1),
       .cin(1'b0),
       // synthesis translate_off
       .sharein(1'b0),
       // synthesis translate_on
       .sumout(),
       .cout(),
       // synthesis translate_off
       .shareout(),
       // synthesis translate_on
       .combout(f4)
   );


   always @(*) begin
      f = f3;
   end

   wire j0, j1, j2, j3, j4, j5;

   tennm_lcell_comb #(
       .lut_mask(64'h117676E8117676E8),
       .extended_lut("off"),
       .shared_arith("off")
   ) wlc7 (
       .dataa(!din_dat[1]),
       .datab(!din_dat[3]),
       .datac(!din_dat[4]),
       .datad(!din_dat[2]),
       .datae(!din_dat[0]),
       .dataf(1'b1),
       .datag(1'b1),
       .datah(1'b1),
       .cin(1'b0),
       // synthesis translate_off
       .sharein(1'b0),
       // synthesis translate_on
       .sumout(),
       .cout(),
       // synthesis translate_off
       .shareout(),
       // synthesis translate_on
       .combout(j0)
   );

   tennm_lcell_comb #(
       .lut_mask(64'h0418182004181820),
       .extended_lut("off"),
       .shared_arith("off")
   ) wlc8 (
       .dataa(!din_dat[1]),
       .datab(!din_dat[3]),
       .datac(!din_dat[4]),
       .datad(!din_dat[2]),
       .datae(!din_dat[0]),
       .dataf(1'b1),
       .datag(1'b1),
       .datah(1'b1),
       .cin(1'b0),
       // synthesis translate_off
       .sharein(1'b0),
       // synthesis translate_on
       .sumout(),
       .cout(),
       // synthesis translate_off
       .shareout(),
       // synthesis translate_on
       .combout(j1)
   );

   tennm_lcell_comb #(
       .lut_mask(64'h5339A6665339A666),
       .extended_lut("off"),
       .shared_arith("off")
   ) wlc9 (
       .dataa(!din_rd),
       .datab(!din_dat[7]),
       .datac(!din_dat[5]),
       .datad(!din_dat[6]),
       .datae(!din_k),
       .dataf(1'b1),
       .datag(1'b1),
       .datah(1'b1),
       .cin(1'b0),
       // synthesis translate_off
       .sharein(1'b0),
       // synthesis translate_on
       .sumout(),
       .cout(),
       // synthesis translate_off
       .shareout(),
       // synthesis translate_on
       .combout(j2)
   );

   tennm_lcell_comb #(
       .lut_mask(64'hF00F0000F00F0000),
       .extended_lut("off"),
       .shared_arith("off")
   ) wlc10 (
       .dataa(1'b1),
       .datab(1'b1),
       .datac(!din_dat[5]),
       .datad(!din_dat[6]),
       .datae(!din_k),
       .dataf(1'b1),
       .datag(1'b1),
       .datah(1'b1),
       .cin(1'b0),
       // synthesis translate_off
       .sharein(1'b0),
       // synthesis translate_on
       .sumout(),
       .cout(),
       // synthesis translate_off
       .shareout(),
       // synthesis translate_on
       .combout(j3)
   );

   tennm_lcell_comb #(
       .lut_mask(64'h0003000000030000),
       .extended_lut("off"),
       .shared_arith("off")
   ) wlc11 (
       .dataa(1'b1),
       .datab(!din_dat[7]),
       .datac(!din_dat[5]),
       .datad(!din_dat[6]),
       .datae(!din_k),
       .dataf(1'b1),
       .datag(1'b1),
       .datah(1'b1),
       .cin(1'b0),
       // synthesis translate_off
       .sharein(1'b0),
       // synthesis translate_on
       .sumout(),
       .cout(),
       // synthesis translate_off
       .shareout(),
       // synthesis translate_on
       .combout(j4)
   );

   tennm_lcell_comb #(
       .lut_mask(64'hF07870A6F07870A6),
       .extended_lut("off"),
       .shared_arith("off")
   ) wlc12 (
       .dataa(!j0),
       .datab(!j1),
       .datac(!j2),
       .datad(!j3),
       .datae(!j4),
       .dataf(1'b1),
       .datag(1'b1),
       .datah(1'b1),
       .cin(1'b0),
       // synthesis translate_off
       .sharein(1'b0),
       // synthesis translate_on
       .sumout(),
       .cout(),
       // synthesis translate_off
       .shareout(),
       // synthesis translate_on
       .combout(j5)
   );


   always @(*) j = j5;


   always @(posedge clk) begin
      dout_val_r <= 0;
      if (din_ena | din_k) begin
         dout_rdreg_r <= dout_rdcomb;
         dout_val_r   <= din_ena | din_k;
         dout_dat_r   <= {j, h, g, f, i, e, d, c, b, a};
      end
      if (sclr) begin
         dout_val_r   <= 1'b0;
         dout_rdreg_r <= 1'b0;
         dout_dat_r   <= 10'b0;
      end
   end
   assign dout_val = dout_val_r;
   assign dout_dat = dout_dat_r;
   assign dout_rdreg = dout_rdreg_r;
   assign dout_rdcomb = dout_rdcomb_r;


endmodule
