// Copyright 2024 Intel Corporation.
//
// This reference design file is subject licensed to you by the terms and 
// conditions of the applicable License Terms and Conditions for Hardware 
// Reference Designs and/or Design Examples (either as signed by you or 
// found at https://www.altera.com/common/legal/leg-license_agreement.html ).  
//
// As stated in the license, you agree to only use this reference design 
// solely in conjunction with Intel FPGAs or Intel CPLDs.  
//
// THE REFERENCE DESIGN IS PROVIDED "AS IS" WITHOUT ANY EXPRESS OR IMPLIED
// WARRANTY OF ANY KIND INCLUDING WARRANTIES OF MERCHANTABILITY, 
// NONINFRINGEMENT, OR FITNESS FOR A PARTICULAR PURPOSE. Intel does not 
// warrant or assume responsibility for the accuracy or completeness of any
// information, links or other items within the Reference Design and any 
// accompanying materials.
//
// In the event that you do not agree with such terms and conditions, do not
// use the reference design file.
/////////////////////////////////////////////////////////////////////////////

// Generated by one of Gregg's toys on Mon Jan 15 15:54:16 2024

`timescale 1ps / 1ps

module eth_8b10b_dec_x4_a (
    input clk,
    input sclr,
    input [39:0] din_dat,
    output [31:0] dout_dat,
    output [3:0] dout_k,
    output [3:0] dout_kerr,
    output [3:0] dout_rderr,
    output [3:0] dout_rdreg
);

   localparam WORDS = 4;
   wire [WORDS-1:0] dout_rdcomb;

   genvar i;
   generate
      for (i = 0; i < WORDS; i = i + 1) begin : lp
         eth_8b10b_dec_a dc0 (
             .clk        (clk),
             .sclr       (sclr),
             .din_ena    (1'b1),                                               // Data (or code) input enable
             .din_dat    (din_dat[(i+1)*10-1:i*10]),                           // 8b data in
             .din_rd     ((i == 0) ? dout_rdreg[WORDS-1] : dout_rdcomb[i-1]),  // running disparity input
             .dout_val   (),
             .dout_kerr  (dout_kerr[i]),
             .dout_dat   (dout_dat[(i+1)*8-1:i*8]),                            // data out
             .dout_k     (dout_k[i]),
             .dout_rderr (dout_rderr[i]),
             .dout_rdcomb(dout_rdcomb[i]),                                     // running disparity output (comb)
             .dout_rdreg (dout_rdreg[i])                                       // running disparity output (reg)
         );
      end
   endgenerate


endmodule
