// Copyright 2024 Intel Corporation.
//
// This reference design file is subject licensed to you by the terms and 
// conditions of the applicable License Terms and Conditions for Hardware 
// Reference Designs and/or Design Examples (either as signed by you or 
// found at https://www.altera.com/common/legal/leg-license_agreement.html ).  
//
// As stated in the license, you agree to only use this reference design 
// solely in conjunction with Intel FPGAs or Intel CPLDs.  
//
// THE REFERENCE DESIGN IS PROVIDED "AS IS" WITHOUT ANY EXPRESS OR IMPLIED
// WARRANTY OF ANY KIND INCLUDING WARRANTIES OF MERCHANTABILITY, 
// NONINFRINGEMENT, OR FITNESS FOR A PARTICULAR PURPOSE. Intel does not 
// warrant or assume responsibility for the accuracy or completeness of any
// information, links or other items within the Reference Design and any 
// accompanying materials.
//
// In the event that you do not agree with such terms and conditions, do not
// use the reference design file.
/////////////////////////////////////////////////////////////////////////////

// Generated by one of Gregg's toys on Mon Jan 15 15:54:16 2024

`timescale 1ps / 1ps

module eth_8b10b_dec_a (
    input clk,
    input sclr,
    input din_ena,
    input [9:0] din_dat,
    input din_rd,
    output [7:0] dout_dat,
    output dout_k,
    output dout_val,
    output dout_kerr,
    output dout_rderr,
    output dout_rdcomb,
    output dout_rdreg
);


   // The decoder reverses the encoding process. Decoding does not depend on the running disparity which
   // simplifies the process somewhat.
   // 

   reg dout_val_r = 1'b0;
   reg [7:0] dout_dat_r = 8'h0;
   reg dout_k_r = 1'b0;
   reg dout_kerr_r = 1'b0;
   reg dout_rderr_r = 1'b0;
   reg dout_rdreg_r = 1'b0;

   wire a = din_dat[0];
   wire b = din_dat[1];
   wire c = din_dat[2];
   wire d = din_dat[3];
   wire e = din_dat[4];
   wire i = din_dat[5];
   wire f = din_dat[6];
   wire g = din_dat[7];
   wire h = din_dat[8];
   wire j = din_dat[9];


   //classification
   wire P04 = (!a & !b & !c & !d);
   wire P13 = (!a & !b & !c & d) | (!a & !b & c & !d) | (!a & b & !c & !d) | (a & !b & !c & !d);
   wire P22 = (!a & !b & c & d) | (!a & b & c & !d) | (a & b & !c & !d) | (a & !b & c & !d) | (a & !b & !c & d) | (!a & b & !c & d);
   wire P31 = (a & b & c & !d) | (a & b & !c & d) | (a & !b & c & d) | (!a & b & c & d);
   wire P40 = (a & b & c & d);


   ////////////////////////////////////////////////
   // data outputs
   ////////////////////////////////////////////////

   wire A = (P22 & !b & !c & !(e ^ i)) ? !a : (P31 & i) ? !a : (P13 & d & e & i) ? !a : (P22 & !a & !c & !(e ^ i)) ? !a : (P13 & !e) ? !a : (a & b & e & i) ? !a : (!c & !d & !e & !i) ? !a : a;
   wire B = (P22 & b & c & !(e ^ i)) ? !b : (P31 & i) ? !b : (P13 & d & e & i) ? !b : (P22 & a & c & !(e ^ i)) ? !b : (P13 & !e) ? !b : (a & b & e & i) ? !b : (!c & !d & !e & !i) ? !b : b;
   wire C = (P22 & b & c & !(e ^ i)) ? !c : (P31 & i) ? !c : (P13 & d & e & i) ? !c : (P22 & !a & !c & !(e ^ i)) ? !c : (P13 & !e) ? !c : (!a & !b & !e & !i) ? !c : (!c & !d & !e & !i) ? !c : c;
   wire D = (P22 & !b & !c & !(e ^ i)) ? !d : (P31 & i) ? !d : (P13 & d & e & i) ? !d : (P22 & a & c & !(e ^ i)) ? !d : (P13 & !e) ? !d : (a & b & e & i) ? !d : (!c & !d & !e & !i) ? !d : d;
   wire E = (P22 & !b & !c & !(e ^ i)) ? !e : (P13 & !i) ? !e : (P13 & d & e & i) ? !e : (P22 & !a & !c & !(e ^ i)) ? !e : (P13 & !e) ? !e : (!a & !b & !e & !i) ? !e : (!c & !d & !e & !i) ? !e : e;


   wire F = (f & h & j) ? !f : (!c & !d & !e & !i & (h ^ j)) ? !f : (!f & !g & h & j) ? !f : (f & g & j) ? !f : (!f & !g & !h) ? !f : (g & h & j) ? !f : f;
   wire G = (!f & !h & !j) ? !g : (!c & !d & !e & !i & (h ^ j)) ? !g : (!f & !g & h & j) ? !g : (f & g & j) ? !g : (!f & !g & !h) ? !g : (!g & !h & !j) ? !g : g;
   wire H = (f & h & j) ? !h : (!c & !d & !e & !i & (h ^ j)) ? !h : (!f & !g & h & j) ? !h : (f & g & j) ? !h : (!f & !g & !h) ? !h : (!g & !h & !j) ? !h : h;


   wire K = (c & d & e & i) | (!c & !d & !e & !i) | (P13 & !e & i & g & h & j) | (P31 & e & !i & !g & !h & !j);


   ////////////////////////////////////////////////
   //running disparity - generate and err check
   ////////////////////////////////////////////////
   wire rd1n = (P04) ? 1'b1 : (P13 & !(e & i)) ? 1'b1 : (P22 & !e & !i) ? 1'b1 : (P13 & d & e & i) ? 1'b1 : 1'b0  /* synthesis keep */;
   wire rd1p = (P40) ? 1'b1 : (P31 & !(!e & !i)) ? 1'b1 : (P22 & e & i) ? 1'b1 : (P31 & !d & !e & !i) ? 1'b1 : 1'b0  /* synthesis keep */;
   wire rd1e = (P13 & !d & e & i) ? 1'b1 : (P22 & (e ^ i)) ? 1'b1 : (P31 & d & !e & !i) ? 1'b1 : 1'b0  /* synthesis keep */;

   wire rd1_err = (!din_rd & rd1n) | (din_rd & rd1p);

   /////////////////////////////
   // factored rd1 generation
   /////////////////////////////
   wire [63:0] rd1_when_din_rd_0_mask = 64'hffe8e880e8808000;
   wire rd1_when_din_rd_0 = rd1_when_din_rd_0_mask[din_dat[5:0]]  /* synthesis keep */;
   wire [63:0] rd1_when_din_rd_1_mask = 64'hfffefee8fee8e800;
   wire rd1_when_din_rd_1 = rd1_when_din_rd_1_mask[din_dat[5:0]]  /* synthesis keep */;
   wire rd1 = din_rd ? rd1_when_din_rd_1 : rd1_when_din_rd_0;

   wire rd2n = (!f & !g & !h) ? 1'b1 : (!f & !g & !j) ? 1'b1 : (!f & !h & !j) ? 1'b1 : (!g & !h & !j) ? 1'b1 : (!f & !g & h & j) ? 1'b1 : 1'b0  /* synthesis keep */;
   wire rd2p = (f & g & h) ? 1'b1 : (f & g & j) ? 1'b1 : (f & h & j) ? 1'b1 : (g & h & j) ? 1'b1 : (f & g & !h & !j) ? 1'b1 : 1'b0  /* synthesis keep */;

   //wire rd2e = ((f ^ g) & (h ^ j)) ? 1'b1 :
   //            0;

   wire rd2_err = (!rd1 & rd2n) | (rd1 & rd2p);


   // these two conditions appear in rd2p and rd2n with the
   // opposite associated rdcomb output.
   wire dout_rdcomb_special = (!f & !g & h & j) | (f & g & !h & !j)  /* synthesis keep */;

   assign dout_rdcomb = (rd2p) ? !dout_rdcomb_special : (rd2n) ? dout_rdcomb_special : rd1;

   ////////////////////////////////////////////////
   // K error check - this is by far the most
   //   complex expression in the decoder. 
   //   It appears to require depth 3.  Please let
   //   me know if you identify a depth 2 mapping.
   ////////////////////////////////////////////////
   wire k_err;
   /////////////////////////////////////
   // use the upper and lower portions only
   // to identify definite errors
   /////////////////////////////////////
   wire [63:0] kerr_mask_ai = 64'h6881800180018117;
   wire [63:0] kerr_mask_ej = 64'hf20000018000004f;
   wire kerr_out_ai = kerr_mask_ai[din_dat[5:0]]  /* synthesis keep */;
   wire kerr_out_ej = kerr_mask_ej[din_dat[9:4]]  /* synthesis keep */;
   wire rd2_err_lc = rd2_err  /* synthesis keep */;

   wire kerr6, kerr7, kerr8, kerr9, kerr_remainder;
   tennm_lcell_comb #(
       .lut_mask(64'h0C0000300C000030),
       .extended_lut("off"),
       .shared_arith("off")
   ) wlc0 (
       .dataa(1'b1),
       .datab(!din_dat[7]),
       .datac(!din_dat[6]),
       .datad(!din_dat[8]),
       .datae(!din_dat[9]),
       .dataf(1'b1),
       .datag(1'b1),
       .datah(1'b1),
       .cin(1'b0),
       // synthesis translate_off
       .sharein(1'b0),
       // synthesis translate_on
       .sumout(),
       .cout(),
       // synthesis translate_off
       .shareout(),
       // synthesis translate_on
       .combout(kerr6)
   );

   tennm_lcell_comb #(
       .lut_mask(64'h0002403000024030),
       .extended_lut("off"),
       .shared_arith("off")
   ) wlc1 (
       .dataa(!din_dat[3]),
       .datab(!din_dat[7]),
       .datac(!din_dat[6]),
       .datad(!din_dat[8]),
       .datae(!din_dat[9]),
       .dataf(1'b1),
       .datag(1'b1),
       .datah(1'b1),
       .cin(1'b0),
       // synthesis translate_off
       .sharein(1'b0),
       // synthesis translate_on
       .sumout(),
       .cout(),
       // synthesis translate_off
       .shareout(),
       // synthesis translate_on
       .combout(kerr7)
   );

   tennm_lcell_comb #(
       .lut_mask(64'h6868960868689608),
       .extended_lut("off"),
       .shared_arith("off")
   ) wlc2 (
       .dataa(!din_dat[0]),
       .datab(!din_dat[1]),
       .datac(!din_dat[2]),
       .datad(!din_dat[4]),
       .datae(!din_dat[3]),
       .dataf(1'b1),
       .datag(1'b1),
       .datah(1'b1),
       .cin(1'b0),
       // synthesis translate_off
       .sharein(1'b0),
       // synthesis translate_on
       .sumout(),
       .cout(),
       // synthesis translate_off
       .shareout(),
       // synthesis translate_on
       .combout(kerr8)
   );

   tennm_lcell_comb #(
       .lut_mask(64'h1001161E1001161E),
       .extended_lut("off"),
       .shared_arith("off")
   ) wlc3 (
       .dataa(!din_dat[0]),
       .datab(!din_dat[1]),
       .datac(!din_dat[2]),
       .datad(!din_dat[4]),
       .datae(!din_dat[3]),
       .dataf(1'b1),
       .datag(1'b1),
       .datah(1'b1),
       .cin(1'b0),
       // synthesis translate_off
       .sharein(1'b0),
       // synthesis translate_on
       .sumout(),
       .cout(),
       // synthesis translate_off
       .shareout(),
       // synthesis translate_on
       .combout(kerr9)
   );

   tennm_lcell_comb #(
       .lut_mask(64'h2331223029110325),
       .extended_lut("off"),
       .shared_arith("off")
   ) wlc4 (
       .dataa(!din_dat[5]),
       .datab(!kerr6),
       .datac(!kerr7),
       .datad(!din_dat[4]),
       .datae(!kerr8),
       .dataf(!kerr9),
       .datag(1'b1),
       .datah(1'b1),
       .cin(1'b0),
       // synthesis translate_off
       .sharein(1'b0),
       // synthesis translate_on
       .sumout(),
       .cout(),
       // synthesis translate_off
       .shareout(),
       // synthesis translate_on
       .combout(kerr_remainder)
   );


   assign k_err = kerr_out_ai | kerr_out_ej | rd2_err_lc & !rd1e | kerr_remainder;

   ////////////////////////////////////////////////
   // output registers
   ////////////////////////////////////////////////
   always @(posedge clk) begin
      dout_val_r <= 1'b0;
      if (din_ena) begin
         dout_k_r <= K;
         dout_val_r <= din_ena;
         dout_dat_r <= {H, G, F, E, D, C, B, A};
         dout_rdreg_r <= dout_rdcomb;
         dout_rderr_r <= (rd1_err | rd2_err);
         dout_kerr_r <= k_err;
      end
      if (sclr) begin
         dout_val_r <= 1'b0;
         dout_k_r <= 1'b0;
         dout_dat_r <= 8'b0;
         dout_rdreg_r <= 1'b0;
         dout_rderr_r <= 1'b0;
         dout_kerr_r <= 1'b0;
      end
   end

   assign dout_val = dout_val_r;
   assign dout_k = dout_k_r;
   assign dout_dat = dout_dat_r;
   assign dout_rdreg = dout_rdreg_r;
   assign dout_rderr = dout_rderr_r;
   assign dout_kerr = dout_kerr_r;


endmodule
