// SPDX-License-Identifier: BSD-2-Clause
// This file defines build-time configuration parameters for the QECIPHY module.
// Please do not edit this file directly. It may be overridden by the build flow.

`ifndef QECIPHY_BUILD_CFG_PKG
`define QECIPHY_BUILD_CFG_PKG

package qeciphy_build_cfg_pkg;

   localparam string QECIPHY_GT_TYPE = "GTY";

endpackage : qeciphy_build_cfg_pkg
`endif
