// SPDX-License-Identifier: BSD-2-Clause
// This file defines configuration parameters for the QECIPHY testbench.
// Please do not edit this file directly. It may be overridden by the build flow.

`ifndef QECIPHY_SIM_CFG_PKG
`define QECIPHY_SIM_CFG_PKG

package qeciphy_sim_cfg_pkg;

   localparam real QECIPHY_RCLK_PERIOD_NS = 6.4;
   localparam real QECIPHY_FCLK_PERIOD_NS = 6.4;

endpackage : qeciphy_sim_cfg_pkg
`endif
